# Generated by Django 6.0.3 on 2026-09-02 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0003_alter_extincteuritem_etat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportEclairage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_job', models.CharField(blank=True, help_text='Champ « JOB » du formulaire papier.', max_length=50)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'Fermé')], default='ouvert', max_length=10)),
                ('date_inspection', models.DateField(blank=True, null=True)),
                ('date_derniere_sauvegarde', models.DateTimeField(auto_now=True)),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_eclairage', to='inspections.batiment')),
                ('cree_par', models.ForeignKey(limit_choices_to={'role': 'superviseur'}, on_delete=django.db.models.deletion.PROTECT, related_name='rapports_eclairage_crees', to=settings.AUTH_USER_MODEL)),
                ('techniciens', models.ManyToManyField(blank=True, limit_choices_to={'role': 'technicien'}, related_name='rapports_eclairage_assignes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueRapportEclairage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='eclairage.rapporteclairage')),
            ],
            options={
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='EclairageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplacement', models.CharField(blank=True, help_text='Localisation', max_length=200)),
                ('etage', models.CharField(blank=True, max_length=100)),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('voltage', models.CharField(blank=True, max_length=50)),
                ('etat', models.CharField(blank=True, choices=[('D', 'Défectueux'), ('C', 'Conforme'), ('NI', 'Non inspecté')], default=None, max_length=2, null=True)),
                ('remarque', models.CharField(blank=True, max_length=300)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lumieres', to='eclairage.rapporteclairage')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
