# Generated by Django 6.0.3 on 2026-09-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclairage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eclairageitem',
            name='emplacement',
            field=models.CharField(blank=True, help_text='Emplacement', max_length=200),
        ),
    ]
