# Generated by Django 6.0.3 on 2026-09-02 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclairage', '0002_alter_eclairageitem_emplacement'),
        ('inspections', '0007_merge_20260902_1007'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rapporteclairage',
            name='rapport_extincteur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapport_eclairage_lie', to='inspections.rapportextincteur'),
        ),
        migrations.AlterField(
            model_name='rapporteclairage',
            name='cree_par',
            field=models.ForeignKey(limit_choices_to={'role__in': ['superviseur', 'technicien']}, on_delete=django.db.models.deletion.PROTECT, related_name='rapports_eclairage_crees', to=settings.AUTH_USER_MODEL),
        ),
    ]
