# Generated by Django 6.0.3 on 2026-09-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_alter_extincteuritem_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extincteuritem',
            name='etat',
            field=models.CharField(blank=True, choices=[('D', 'Défectueux'), ('C', 'Conforme'), ('NI', 'Non inspecté')], default=None, max_length=2, null=True),
        ),
    ]
