# Generated by Django 6.0.3 on 2026-08-30 22:35, hand-edited: date_fabrication,
# prochaine_maintenance et prochain_test_hydrostatique passent de DateField à
# PositiveIntegerField (année seule). Une ALTER COLUMN ... TYPE integer directe
# échoue sur PostgreSQL (date -> integer n'est pas un cast implicite) — on
# convertit donc les données existantes via EXTRACT(YEAR FROM ...) pour ne pas
# perdre les valeurs déjà saisies.

import django.core.validators
from django.db import migrations, models


def _alter_annee(nom_colonne):
    return migrations.RunSQL(
        sql=(
            f'ALTER TABLE inspections_extincteuritem '
            f'ALTER COLUMN {nom_colonne} TYPE integer '
            f'USING EXTRACT(YEAR FROM {nom_colonne})::integer;'
        ),
        reverse_sql=(
            f'ALTER TABLE inspections_extincteuritem '
            f'ALTER COLUMN {nom_colonne} TYPE date '
            f"USING make_date({nom_colonne}, 1, 1);"
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_alter_extincteuritem_etat'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                _alter_annee('date_fabrication'),
                _alter_annee('prochaine_maintenance'),
                _alter_annee('prochain_test_hydrostatique'),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='extincteuritem',
                    name='date_fabrication',
                    field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
                ),
                migrations.AlterField(
                    model_name='extincteuritem',
                    name='prochain_test_hydrostatique',
                    field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
                ),
                migrations.AlterField(
                    model_name='extincteuritem',
                    name='prochaine_maintenance',
                    field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='extincteuritem',
            name='etat',
            field=models.CharField(blank=True, choices=[('D', 'Défectueux'), ('C', 'Conforme'), ('NI', 'Non inspecté')], default=None, max_length=2, null=True),
        ),
    ]
