# Generated by Django 6.0.3 on 2026-08-30 23:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_alter_extincteuritem_format_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoyauItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etage', models.CharField(blank=True, max_length=100)),
                ('etat', models.CharField(blank=True, choices=[('D', 'Défectueux'), ('C', 'Conforme'), ('NI', 'Non inspecté')], default=None, max_length=2, null=True)),
                ('emplacement', models.CharField(blank=True, max_length=200)),
                ('longueur', models.CharField(blank=True, choices=[('50pi', '50 pi'), ('75pi', '75 pi'), ('100pi', '100 pi'), ('autre', 'Autre')], max_length=10)),
                ('date_fabrication', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('prochain_test_hydrostatique', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('remarque', models.CharField(blank=True, max_length=300)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boyaux', to='inspections.rapportextincteur')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
