# Generated by Django 6.0.3 on 2026-08-30 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_boyauitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportextincteur',
            name='cree_par',
            field=models.ForeignKey(limit_choices_to={'role__in': ['superviseur', 'technicien']}, on_delete=django.db.models.deletion.PROTECT, related_name='rapports_extincteurs_crees', to=settings.AUTH_USER_MODEL),
        ),
    ]
