# Generated by Django 6.0.3 on 2026-09-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_alter_extincteuritem_etat'),
        ('inspections', '0006_alter_rapportextincteur_cree_par'),
    ]

    operations = [
    ]
