# Generated by Django 6.0.3 on 2026-09-03 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0007_merge_20260902_1007'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportAlarme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_job', models.CharField(blank=True, help_text='Champ « JOB » du formulaire papier.', max_length=50)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'Fermé')], default='ouvert', max_length=10)),
                ('date_inspection', models.DateField(blank=True, null=True)),
                ('date_derniere_sauvegarde', models.DateTimeField(auto_now=True)),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_alarme', to='inspections.batiment')),
                ('cree_par', models.ForeignKey(limit_choices_to={'role__in': ['superviseur', 'technicien']}, on_delete=django.db.models.deletion.PROTECT, related_name='rapports_alarme_crees', to=settings.AUTH_USER_MODEL)),
                ('rapport_extincteur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapport_alarme_lie', to='inspections.rapportextincteur')),
                ('techniciens', models.ManyToManyField(blank=True, limit_choices_to={'role': 'technicien'}, related_name='rapports_alarme_assignes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueRapportAlarme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='inspections.rapportalarme')),
            ],
            options={
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='FicheLegende',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositifs', models.JSONField(blank=True, default=dict, help_text="JSON par code d'abréviation : { 'PAI': {'type': '', 'modele': ''}, ... }")),
                ('rapport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_legende', to='inspections.rapportalarme')),
            ],
        ),
        migrations.CreateModel(
            name='FicheE2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localisation', models.CharField(blank=True, max_length=200)),
                ('description_panneau', models.CharField(blank=True, max_length=200)),
                ('tension_sous_alimentation', models.CharField(blank=True, max_length=20)),
                ('tension_pleine_charge', models.CharField(blank=True, max_length=20)),
                ('courant_charge', models.CharField(blank=True, max_length=20)),
                ('code_dateur_batterie', models.CharField(blank=True, max_length=10)),
                ('signal_alarme_ok', models.BooleanField(blank=True, null=True)),
                ('rearmement_ok', models.BooleanField(blank=True, null=True)),
                ('commutation_alimentation_ok', models.BooleanField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text="JSON structuré de toutes les sous-sections E2.1 à E2.12. Format : { 'e2_1': { 'localisation': '', 'description': '', 'items': { 'A': 'oui', 'B': 'sans_objet', ... } }, ... }")),
                ('rapport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_e2', to='inspections.rapportalarme')),
            ],
        ),
        migrations.CreateModel(
            name='FicheE1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonctionnement_une_etape', models.BooleanField(blank=True, null=True)),
                ('fonctionnement_deux_etapes', models.BooleanField(blank=True, null=True)),
                ('inspection_essai_conforme', models.BooleanField(blank=True, null=True)),
                ('documentation_sur_place', models.BooleanField(blank=True, null=True)),
                ('reseau_fonctionnel', models.BooleanField(blank=True, null=True)),
                ('lacunes_constatees', models.BooleanField(blank=True, null=True)),
                ('commentaires', models.TextField(blank=True)),
                ('copie_remise_responsable', models.BooleanField(blank=True, null=True)),
                ('date_signature', models.DateTimeField(blank=True, null=True)),
                ('signataire', models.ForeignKey(blank=True, help_text='La personne qui a fermé le rapport — certifie que les renseignements sont exacts et complets.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_e1_signees', to=settings.AUTH_USER_MODEL)),
                ('rapport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_e1', to='inspections.rapportalarme')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeSommaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations_generales', models.TextField(blank=True)),
                ('resume_citoyen', models.TextField(blank=True, help_text='Résumé en langage simple, sans jargon technique, destiné au citoyen.')),
                ('rapport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_sommaire', to='inspections.rapportalarme')),
            ],
        ),
        migrations.CreateModel(
            name='EtageResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex. « Sous-sol », « 3e étage »', max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('etat', models.CharField(choices=[('bon', 'Bon'), ('acceptable', 'Acceptable'), ('a_reviser', 'À réviser')], default='bon', max_length=20)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etages', to='inspections.resumesommaire')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SectionDispositif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='inspections.rapportalarme')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Dispositif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localisation', models.CharField(help_text='Emplacement précis dans la section — ex. « App. 312 »', max_length=200)),
                ('type_dispositif', models.CharField(blank=True, choices=[('S', 'Détecteur de fumée'), ('RHT', 'Détecteur de chaleur réarmable'), ('HT', 'Détecteur de chaleur non réarmable'), ('M', 'Avertisseur manuel'), ('B', 'Cloche'), ('AFE', 'Avertisseur de fumée électrique'), ('UN72-6', "Éclairage d'urgence"), ('PAI', "Panneau d'alarme incendie"), ('K', 'Klaxon'), ('FDL', 'Résistance de fin de ligne'), ('PZ', 'Piézo'), ('ISO', 'Module isolateur'), ('ANN', "Panneau annonciateur d'alarme"), ('DFG', 'Détecteur de fumée gaine ventilation'), ('TEL', "Téléphone d'urgence (pompier)"), ('IDG', 'Gicleur débit'), ('IVG', 'Interrupteur vanne gicleur'), ('IHP', 'Interrupteur haute pression'), ('IBH', 'Interrupteur de basse pression'), ('K/S', 'Klaxon strobe'), ('MA', 'Module adressable')], default=None, max_length=10, null=True)),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('installation_correcte', models.BooleanField(blank=True, default=None, null=True)),
                ('necessite_entretien', models.BooleanField(blank=True, default=None, null=True)),
                ('alarme_confirmee', models.BooleanField(blank=True, default=None, null=True)),
                ('annonce_statut', models.CharField(blank=True, choices=[('D', 'Défectueux'), ('I', 'Inspecté'), ('NI', 'Non inspecté')], default=None, max_length=2, null=True)),
                ('zone_circuit', models.CharField(blank=True, max_length=20)),
                ('remarque', models.CharField(blank=True, max_length=300)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositifs', to='inspections.rapportalarme')),
                ('section', models.ForeignKey(blank=True, help_text="La zone/l'étage auquel ce dispositif appartient.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispositifs', to='inspections.sectiondispositif')),
            ],
            options={
                'ordering': ['section__ordre', 'id'],
            },
        ),
    ]
