# Generated by Django 6.0.3 on 2026-09-03 21:25

from django.db import migrations, models


def _inspecte_vers_conforme(apps, schema_editor):
    """Le code 'I' (Inspecté) devient 'C' (Conforme) — même convention que
    les extincteurs et l'éclairage d'urgence dans le reste de l'app."""
    Dispositif = apps.get_model('inspections', 'Dispositif')
    Dispositif.objects.filter(annonce_statut='I').update(annonce_statut='C')


def _conforme_vers_inspecte(apps, schema_editor):
    Dispositif = apps.get_model('inspections', 'Dispositif')
    Dispositif.objects.filter(annonce_statut='C').update(annonce_statut='I')


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0008_rapportalarme_historiquerapportalarme_fichelegende_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batiment',
            name='fabricant_reseau',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='batiment',
            name='modele_systeme',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dispositif',
            name='annonce_statut',
            field=models.CharField(blank=True, choices=[('D', 'Défectueux'), ('C', 'Conforme'), ('NI', 'Non inspecté')], default=None, max_length=2, null=True),
        ),
        migrations.RunPython(_inspecte_vers_conforme, _conforme_vers_inspecte),
    ]
