# Generated by Django 6.0.3 on 2026-09-03 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0009_batiment_fabricant_reseau_batiment_modele_systeme_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportalarme',
            name='citoyen',
            field=models.ForeignKey(blank=True, help_text='Le citoyen qui pourra consulter ce rapport et son certificat.', limit_choices_to={'role': 'citoyen'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_alarme_citoyen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CertificatAlarme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('certificat_envoye', models.BooleanField(default=False, help_text='True quand le superviseur envoie explicitement le certificat au citoyen.')),
                ('emis_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificats_alarme_emis', to=settings.AUTH_USER_MODEL)),
                ('rapport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificat', to='inspections.rapportalarme')),
            ],
            options={
                'ordering': ['-date_emission'],
            },
        ),
    ]
