# Generated by Django 6.0.3 on 2026-09-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0011_rapportcuisine_hottecuisine_historiquerapportcuisine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportcuisine',
            name='date_installation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rapportcuisine',
            name='dispositif_coupure',
            field=models.CharField(blank=True, choices=[('valve_gaz', 'Valve(s) à gaz'), ('contacteur', 'Contacteur')], max_length=15),
        ),
        migrations.AddField(
            model_name='rapportcuisine',
            name='liens_fusibles_360f',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Liens fusibles 360°F'),
        ),
        migrations.AddField(
            model_name='rapportcuisine',
            name='liens_fusibles_450f',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Liens fusibles 450°F'),
        ),
        migrations.AddField(
            model_name='rapportcuisine',
            name='liens_fusibles_500f',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Liens fusibles 500°F'),
        ),
        migrations.AddField(
            model_name='rapportcuisine',
            name='nombre_buses',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre total de buses du système', null=True),
        ),
        migrations.AlterField(
            model_name='rapportcuisine',
            name='alimentation',
            field=models.CharField(blank=True, help_text='Ex. « Gaz », « Électrique »', max_length=150),
        ),
    ]
