# Generated by Django 6.0.3 on 2026-09-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0013_hottecuisine_buses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositif',
            name='annonce_statut',
            field=models.CharField(blank=True, choices=[('D', 'Défectueux'), ('I', 'Inspecté'), ('NI', 'Non inspecté')], default=None, max_length=2, null=True),
        ),
    ]
