# Generated by Django 6.0.3 on 2026-09-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0014_alter_dispositif_annonce_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='hottecuisine',
            name='elevations',
            field=models.JSONField(blank=True, default=list, help_text="Positions horizontales des conduits d'évacuation verticaux (raccords vers le toit), placés manuellement — [{'x': 250}, ...]."),
        ),
        migrations.AlterField(
            model_name='hottecuisine',
            name='buses',
            field=models.JSONField(blank=True, default=list, help_text="Positions horizontales des buses, placées manuellement — [{'x': 120, 'direction': 'gauche'|'droite'}, ...], comme `appareils`. `direction` absente = buse verticale (droit devant)."),
        ),
    ]
