# Generated by Django 6.0.3 on 2026-09-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0015_hottecuisine_elevations_alter_hottecuisine_buses'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportcuisine',
            name='conforme_recommandations',
            field=models.BooleanField(blank=True, default=None, help_text='Décision du technicien (« À cette date, le système... est conforme / nécessite des modifications ») — quand renseignée, remplace le calcul automatique basé sur la checklist pour déterminer la conformité affichée sur le certificat.', null=True),
        ),
    ]
