# Generated by Django 6.0.3 on 2026-09-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0016_rapportcuisine_conforme_recommandations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositif',
            name='rapport',
        ),
        migrations.RemoveField(
            model_name='dispositif',
            name='section',
        ),
        migrations.RemoveField(
            model_name='etageresume',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='fichee1',
            name='rapport',
        ),
        migrations.RemoveField(
            model_name='fichee1',
            name='signataire',
        ),
        migrations.RemoveField(
            model_name='fichee2',
            name='rapport',
        ),
        migrations.RemoveField(
            model_name='fichelegende',
            name='rapport',
        ),
        migrations.RemoveField(
            model_name='historiquerapportalarme',
            name='rapport',
        ),
        migrations.RemoveField(
            model_name='historiquerapportalarme',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='rapportalarme',
            name='batiment',
        ),
        migrations.RemoveField(
            model_name='rapportalarme',
            name='citoyen',
        ),
        migrations.RemoveField(
            model_name='rapportalarme',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='rapportalarme',
            name='rapport_extincteur',
        ),
        migrations.RemoveField(
            model_name='rapportalarme',
            name='techniciens',
        ),
        migrations.RemoveField(
            model_name='sectiondispositif',
            name='rapport',
        ),
        migrations.RemoveField(
            model_name='resumesommaire',
            name='rapport',
        ),
        migrations.RemoveField(
            model_name='batiment',
            name='fabricant_reseau',
        ),
        migrations.RemoveField(
            model_name='batiment',
            name='modele_systeme',
        ),
        migrations.DeleteModel(
            name='CertificatAlarme',
        ),
        migrations.DeleteModel(
            name='Dispositif',
        ),
        migrations.DeleteModel(
            name='EtageResume',
        ),
        migrations.DeleteModel(
            name='FicheE1',
        ),
        migrations.DeleteModel(
            name='FicheE2',
        ),
        migrations.DeleteModel(
            name='FicheLegende',
        ),
        migrations.DeleteModel(
            name='HistoriqueRapportAlarme',
        ),
        migrations.DeleteModel(
            name='SectionDispositif',
        ),
        migrations.DeleteModel(
            name='RapportAlarme',
        ),
        migrations.DeleteModel(
            name='ResumeSommaire',
        ),
    ]
