# Generated by Django 6.0.3 on 2026-09-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0018_code_grille_charbon_gc'),
    ]

    operations = [
        migrations.AddField(
            model_name='hottecuisine',
            name='tailles',
            field=models.JSONField(blank=True, default=list, help_text="Petits carrés « taille de hotte » (en pieds) placés à l'intérieur de la hotte — [{'x': 120, 'pieds': 6}, ...]."),
        ),
    ]
