# Generated by Django 6.0.3 on 2026-09-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0019_hotte_tailles'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatcuisine',
            name='date_envoi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificatcuisine',
            name='envoye_a',
            field=models.CharField(blank=True, help_text="Courriel (envoi direct) ou nom d'utilisateur du citoyen.", max_length=254),
        ),
        migrations.AddField(
            model_name='certificatcuisine',
            name='mode_envoi',
            field=models.CharField(blank=True, choices=[('direct', 'Courriel direct'), ('citoyen', 'Espace citoyen')], max_length=20),
        ),
        migrations.AddField(
            model_name='certificatextincteur',
            name='date_envoi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificatextincteur',
            name='envoye_a',
            field=models.CharField(blank=True, help_text="Courriel (envoi direct) ou nom d'utilisateur du citoyen.", max_length=254),
        ),
        migrations.AddField(
            model_name='certificatextincteur',
            name='mode_envoi',
            field=models.CharField(blank=True, choices=[('direct', 'Courriel direct'), ('citoyen', 'Espace citoyen')], max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='mode_livraison',
            field=models.CharField(choices=[('plateforme', 'Espace client (invitation)'), ('direct', 'Envoi direct par courriel (PDF joint)')], default='plateforme', help_text='« Direct » : pas de compte à créer — les rapports et certificats PDF sont envoyés directement à contact_email. Recommandé pour les clients avec peu de bâtiments.', max_length=20),
        ),
    ]
