# Generated by Django 6.1.1 on 2026-10-05 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0020_envoi_direct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiquerapportcuisine',
            name='rapport',
        ),
        migrations.RemoveField(
            model_name='historiquerapportcuisine',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='hottecuisine',
            name='rapport',
        ),
        migrations.RemoveField(
            model_name='rapportcuisine',
            name='batiment',
        ),
        migrations.RemoveField(
            model_name='rapportcuisine',
            name='citoyen',
        ),
        migrations.RemoveField(
            model_name='rapportcuisine',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='rapportcuisine',
            name='rapport_extincteur',
        ),
        migrations.RemoveField(
            model_name='rapportcuisine',
            name='techniciens',
        ),
        migrations.DeleteModel(
            name='CertificatCuisine',
        ),
        migrations.DeleteModel(
            name='HistoriqueRapportCuisine',
        ),
        migrations.DeleteModel(
            name='HotteCuisine',
        ),
        migrations.DeleteModel(
            name='RapportCuisine',
        ),
    ]
