# Generated by Django 6.0.3 on 2026-10-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0021_suppression_systeme_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='extincteuritem',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
