# Generated by Django 6.0.3 on 2026-10-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0022_extincteur_numero_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='batiment',
            name='nom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='batiment',
            name='province',
            field=models.CharField(blank=True, default='Québec', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_cellulaire',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='extincteuritem',
            name='code_equipement',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='extincteuritem',
            name='non_conformites',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rapportextincteur',
            name='frequence',
            field=models.CharField(choices=[('mensuelle', 'Mensuelle'), ('annuelle', 'Annuelle')], default='annuelle', max_length=10),
        ),
    ]
