# Generated by Django 6.0.3 on 2026-10-05 18:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0023_batiment_nom_batiment_province_client_code_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extincteuritem',
            name='dernier_test_hydrostatique',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='extincteuritem',
            name='modele',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='extincteuritem',
            name='numero',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='extincteuritem',
            name='format',
            field=models.CharField(blank=True, choices=[('2.5lb', '2.5 lb'), ('5lb', '5 lb'), ('10lb', '10 lb'), ('13.25lb', '13.25 lb'), ('15lb', '15 lb'), ('20lb', '20 lb'), ('30lb', '30 lb'), ('50lb', '50 lb'), ('125lb', '125 lb'), ('2.5kg', '2.5 kg'), ('5kg', '5 kg'), ('10kg', '10 kg'), ('6L', '6 L'), ('autre', 'Autre')], max_length=10),
        ),
        migrations.AlterField(
            model_name='extincteuritem',
            name='marque',
            field=models.CharField(blank=True, choices=[('amerex', 'Amerex'), ('kidde', 'Kidde'), ('buckeye', 'Buckeye'), ('ansul', 'Ansul'), ('general', 'General'), ('flag', 'Flag'), ('strikefirst', 'Strike First'), ('badger', 'Badger'), ('pyrene', 'Pyrene'), ('sentry', 'Sentry'), ('pyrochem', 'Pyro Chem'), ('autre', 'Autre')], max_length=15),
        ),
        migrations.AlterField(
            model_name='extincteuritem',
            name='type_extincteur',
            field=models.CharField(blank=True, choices=[('ABC', 'Poudre ABC'), ('BC', 'Poudre BC'), ('CO2', 'CO2'), ('EAU', 'Eau'), ('AFFF', 'Mousse (AFFF)'), ('K', 'Produits chimiques humides (K)'), ('halotron', 'Halotron'), ('fe36', 'FE36'), ('PK', 'Purple K (PK)'), ('D', 'Classe D (métaux)'), ('autre', 'Autre')], max_length=10),
        ),
        migrations.CreateModel(
            name='SectionExtincteurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='inspections.rapportextincteur')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.AddField(
            model_name='extincteuritem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extincteurs', to='inspections.sectionextincteurs'),
        ),
    ]
